### PR TITLE
Add `vat_reference` to shipments 

### PR DESCRIPTION
**Pull request by jbuyco**
**Description**

A new shipment field was added via https://github.com/venturemedia/chitchats/pull/3131. This adds a short description as to how to include this information in an API create request.

### CODE REVIEW

**Review by rajbirverma — APPROVED** [review]
👍

**Comment by vzeazy** [comment]
Possibly better to have same field reference as csv import (customs_tax_reference) for consistency.

**Comment by jbuyco** [comment]
@vzeazy The CSV import field is also `vat_reference`. Is this documented elsewhere?

**Comment by jbuyco** [comment]
Noted blog post indicates `customs_tax_reference` as the CSV field instead of `vat_reference`: https://chitchats.com/blog/eu-vat-changes-upcoming-july-1

Thanks for the heads-up @vzeazy, I've reached out to our team to have this corrected. If you noticed this elsewhere, I'll ensure the documentation is updated.

**Comment by vzeazy** [comment]
Great, thanks. Can confirm this is the source I was referencing for the discrepancy.

**Pull request merged**
